### ISSUE TITLE
src path messed up

### ISSUE THREAD

**Issue by FloydATC** [Ano-Tech-Computers/BanPlugin#1]
I don't know why but the src path was inconsistent, when I imported the project the source files were missing and when I committed the new source files the repo ended up with two paths;
"no/atc/floyd/bukkit/ban"
"src/no/atc/floyd/bukkit/ban"
Comparing with TelePlugin, it seems to me the first one is incorrect.

**Comment by osvein** [comment]
Whoops!

When importing the source code, I lethargically assumed that the provided jars had preserved the workspace structure.

Every project imported from jars seems to have this issue.

**Comment by FloydATC** [comment]
Makes sense. Can you fix it?
